project:
  type: book

book:
  title: "DevOps for Data Science"
  author: "Alex K Gold"
  page-footer:
    left: "Copyright 2021, Alex K Gold"
    right:
      - icon: github
        href: https://github.com/akgold/do4ds
      - icon: twitter
        href: https://twitter.com/alexkgold
  search: true
  repo-url: https://github.com/akgold/do4ds
  repo-actions: [edit]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: "DevOps Lessons for Data Science"
      chapters:
      - chapters/sec1/cmd-line.qmd
      - chapters/sec1/code-promotion.qmd
      - chapters/sec1/repro-pkgs.qmd
      - chapters/sec1/docker.qmd
      - chapters/sec1/data.qmd
      - chapters/sec1/cloud.qmd
    - part: "Your Own Data Science Workbench"
      chapters:
      - chapters/sec2/servers.qmd
      - chapters/sec2/aws-walkthrough.qmd
      - chapters/sec2/understanding-traffic.qmd
      - chapters/sec2/using-urls.qmd
      - chapters/sec2/private-network-config.qmd
    - part: "Working with Enterprise IT"
      chapters:
      - chapters/sec3/auth.qmd
      - chapters/sec3/offline.qmd
      - chapters/sec3/scaling.qmd
  appendices:
    - chapters/append/env-req.qmd
    - chapters/append/terminal.qmd
    - chapters/append/linux-cmd.qmd

bibliography: references.bib

format:
  html:
    theme: flatly

editor: visual

