project:
  type: book

book:
  title: "DevOps for Data Science"
  author: "Alex K Gold"
  page-footer:
    left: "Copyright 2022, Alex K Gold"
    right:
      - icon: github
        href: https://github.com/akgold/do4ds
      - icon: twitter
        href: https://twitter.com/alexkgold
  search: true
  site-url: https://do4ds.com
  repo-url: https://github.com/akgold/do4ds
  repo-actions: [edit]
  sharing: [twitter, facebook]
  google-analytics: "G-BTSMMRMH08"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: chapters/sec1/sec-intro.qmd
      chapters:
      - chapters/sec1/code-promotion.qmd
      - chapters/sec1/env-as-code.qmd
      - chapters/sec1/proj-components.qmd
      - chapters/sec1/monitor-log.qmd
      - chapters/sec1/docker.qmd
    - part: chapters/sec2/sec-intro.qmd
      chapters:
      - chapters/sec2/cloud.qmd
      - chapters/sec2/cmd-line.qmd
      - chapters/sec2/linux-admin.qmd
      - chapters/sec2/understanding-traffic.qmd
      - chapters/sec2/servers.qmd
    - part: chapters/sec3/sec-intro.qmd
      chapters:
      - chapters/sec3/env-promote.qmd
      - chapters/sec3/offline.qmd
      - chapters/sec3/auth.qmd
      - chapters/sec3/scaling.qmd


  appendices:
    - chapters/append/docker-cheatsheet.qmd

#bibliography: references.bib

format:
  html:
    theme: flatly

editor: visual

