project:
  type: book

book:
  title: "DevOps for Data Science"
  author: "Alex K Gold"
  page-footer:
    left: "Copyright 2022, Alex K Gold"
    right:
      - icon: github
        href: https://github.com/akgold/do4ds
      - icon: twitter
        href: https://twitter.com/alexkgold
  search: true
  repo-url: https://github.com/akgold/do4ds
  repo-actions: [edit]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: "DevOps for Data Scientists"
      chapters:
      - chapters/sec1/code-promotion.qmd
      - chapters/sec1/repro-pkgs.qmd
      - chapters/sec1/docker.qmd
      - chapters/sec1/data.qmd
    - part: chapters/sec2/sec-intro.qmd
      chapters:
      - chapters/sec2/servers.qmd
      - chapters/sec2/auth.qmd
      - chapters/sec2/offline.qmd
      - chapters/sec2/scaling.qmd
    - part: "Your Own Data Science Workbench"
      chapters:
      - chapters/sec3/cloud.qmd
      - chapters/sec3/cmd-line.qmd
      - chapters/sec3/aws-walkthrough.qmd
      - chapters/sec3/understanding-traffic.qmd
      - chapters/sec3/using-urls.qmd

  appendices:
    - chapters/append/env-req.qmd
    - chapters/append/terminal.qmd
    - chapters/append/linux-cmd.qmd

bibliography: references.bib

format:
  html:
    theme: flatly

editor: visual

