on:
  push:
     branches:
       - main

name: renderbook

jobs:
  render-book:
    name: Render-Book
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout
      - uses: quarto-dev/quarto-actions/install-quarto@v1
      - run: |
          quarto --version
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
        env:
          RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/all/latest

      - name: Render Book
        run: |
          quarto render .
      - uses: actions/upload-artifact
        with:
          name: _site
          path: _book/

# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: render-book
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact
       with:
         name: _site
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          email: alexkgold@gmail.com


